# Generated by Django 5.0.6 on 2024-08-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagi_college', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Department1',
        ),
    ]
