# Generated by Django 5.0.6 on 2024-07-15 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_choices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='FYStudent',
        ),
    ]
