# Generated by Django 5.0.6 on 2024-07-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_choices', '0002_rename_student_fystudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fystudent',
            name='name',
            field=models.CharField(default='Not Available', max_length=100),
            preserve_default=False,
        ),
    ]
