# Generated by Django 5.0.6 on 2024-07-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_choices', '0003_fystudent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fystudent',
            name='role',
            field=models.CharField(choices=[('MGR', 'Manager'), ('DEV', 'Developer'), ('INT', 'Intern')], default='INT', max_length=3),
        ),
        migrations.AddField(
            model_name='fystudent',
            name='status',
            field=models.IntegerField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Done')], default=1),
        ),
    ]
