# Generated by Django 5.0.6 on 2024-07-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_choices', '0004_fystudent_role_fystudent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fystudent',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
