# Generated by Django 5.0.6 on 2024-07-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_choices', '0007_alter_fystudent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SY',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('division', models.CharField(choices=[('A', 'Devision A'), ('B', 'Devision B'), ('C', 'Devision C'), ('D', 'Devision D')], max_length=1)),
            ],
            options={
                'verbose_name': 'SY Student Data',
                'verbose_name_plural': 'SY Student Records',
                'ordering': ['division', 'name'],
            },
        ),
    ]
