# Generated by Django 5.0.6 on 2024-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_choices', '0011_alter_sy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sy',
            options={'ordering': ['division', '-name'], 'verbose_name': 'SY Student Data', 'verbose_name_plural': 'SY Student Records'},
        ),
        migrations.AddIndex(
            model_name='sy',
            index=models.Index(condition=models.Q(('division', 'A')), fields=['name'], name='division_A_index'),
        ),
    ]
