# Generated by Django 5.0.6 on 2024-07-16 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_choices', '0012_alter_sy_options_sy_division_a_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='sy',
            name='marks',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
