# Generated by Django 5.0.6 on 2024-07-16 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_choices', '0013_sy_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('marks', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sy',
            name='elective',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dj_choices.elective'),
        ),
    ]
