# Generated by Django 5.0.6 on 2024-07-16 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_choices', '0014_elective_sy_elective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sy',
            name='elective',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='dj_choices.elective'),
        ),
    ]
