# Generated by Django 5.0.6 on 2024-07-16 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_choices', '0016_department_sy_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sy',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='dj_choices.department'),
        ),
    ]
