# Generated by Django 5.0.6 on 2024-07-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_choices', '0017_alter_sy_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elective',
            name='subject',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
