# Generated by Django 5.0.6 on 2024-07-20 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_choices', '0018_alter_elective_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sy',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dj_choices.department'),
        ),
    ]
