# Generated by Django 5.0.7 on 2024-09-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_views', '0003_state_created_at_state_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='form_date',
            field=models.DateField(null=True),
        ),
    ]
