# Generated by Django 5.0.7 on 2024-09-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_views', '0004_state_form_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='form_date',
        ),
    ]
